---
title: "Identifying optimal baselines for stable isotope studies of stream food webs"
author: 
  - "Nathan Barrus^1^, Bryan M. Maitland^1,2^, Frank J, Rahel^1^"
  - "^1^University of Wyoming" 
  - "^2^UW-Madison and WDNR"
date: "`r format(Sys.time(), '%Y-%B-%d')`"
output: 
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
  bookdown::html_document2:
    number_sections: false
  # word_document: default
fontsize: 11pt
geometry: margin = 1in
header-includes:
- \usepackage{setspace}\doublespacing
- \usepackage[left]{lineno}
- \linenumbers
- \usepackage{url}
- \usepackage{dcolumn}
- \usepackage{caption}
- \usepackage{float}
- \usepackage{afterpage}
- \usepackage{siunitx}
- \usepackage{amsmath}
bibliography: baseline-isotopes.bib
csl: freshwater-biology.csl
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{css, echo=FALSE}
h1, h4.author, h4.date {
  text-align: center;
}

h1 {
  font-weight: bold;
}
```


**Keywords**: 

**Type of manuscript**: Article

**Manuscript structure**: Abstract = xxx words, main text = xxxx words, tables = x, figures = x, references = xx. 

**Statement of authorship**: NTB and BMM conceived the ideas and designed methodology; NTB and BMM collected the data; NTB analyzed the data; NTB led the writing of the manuscript. All authors contributed critically to the drafts and gave final approval for publication.

**Data accessibility statement**: Should this manuscript be accepted, the data and code supporting the results will be archived on GitHub and in the Zenodo public repository.

**Conflict of Interests**: None to declare. 

\newpage


## Abstract

Stable isotope analysis (SIA) is used in aquatic ecosystems to reconstruct food webs and deduce trophic interactions. Because land use strongly influence d15N values in consumers, suitable isotopic baselines must be established for meaningful cross-site comparisons of food webs. 
Our objective was to identify an invertebrate taxon or Functional Feeding Group (FFG) useful as a baseline for d15N values in riverine food webs. The ideal baseline should meet four criteria: 1) be easy to collect with wide geographic distribution, 2) have low within-site d15N variation among individuals, 3) have d15N values that are correlated with land use and background d15N values, and 4) produce no systemic change in calculated consumer trophic positions with % land use (i.e. be independent of system-specific d15N variability).  We investigated these criteria in invertebrate communities in 16 sites along a gradient from mountain to prairie streams which also represent a gradient in land use. 

Two invertebrate families, Simuliidae and Ephemeridae, and the FFG of Filterers fulfilled all four criteria, similar to ideal indicator taxa identified in Danish lowland streams. Interestingly, even after correcting for local variation in baseline d15N values, the trophic position of some fish species still varied along the longitudinal stream gradient. This difference is most likely explained by actual differences in trophic positions of these species due to dietary changes across the stream gradient. 

Using the FFG Filterers is a potentially better baseline in that it incorporates data from less common but still meaningful taxa (i.e. long-lived bivalves are typically Filterers).  Accurate and meaningful baselines will become increasingly important as SIA develops from a qualitative to quantitative tool for understanding food webs and trophic interactions. 


Problem: d15N values vary in freshwater systems, e.g., reflecting variations in land use, so suitable baseline indicators must be specified to permit cross-site comparisons, and few methodical SOPs have been developed.

Main takeaways
* Simulidae fulfilled all criteria
* TP estimates based on simulids or grouped filterers were independent of land use change
* Diet did not change across land use gradient (mixing models)
* Simulids had lowest within-site variation (similar feeding habit; integrating seston)
* Simulids / filterers can be suitable baseline indicators

We suggest that future investigators follow a similar trial and-error method to identify potential baselines in other types of freshwater systems and biomes. A set of reliable baselines that could be used readily would facilitate studies of freshwater food webs.


## Introduction

Stable isotope analysis (SIA) is a commonly-used tool for making inferences about the trophic structure and flow of materials in food webs. Stable isotope ratios—typically of carbon (13C/12C, d13C) or nitrogen (15N/14N, d15N)—provide information on the materials assimilated by animals because of predictable changes in isotopic composition that occur in body tissues during elemental incorporation of diet items [@VanderZanden1997; @Perkins2014]. With each trophic transfer, carbon isotope ratios change little which makes them useful for tracking energy pathways from basal resources and identifying the ultimate carbon source supporting consumers. In contrast, nitrogen isotope ratios change markedly and predictably with each trophic transfer, allowing for inference into species’ trophic positions in communities, as well quantification of whole-community food chain length (Post, 2002; Mccutchan et al., 2016; Pinzone et al., 2017).  

However, large spatial variability in the nitrogen isotope ratios—that is, d15N values—of aquatic organisms can make the comparison of food webs among sites or along environmental  gradients problematic (Anderson & Cabana, 2005; Barnes et al., 2008).  Such variability arises from natural processes such as denitrification and nitrogen fixation, but also and importantly from land use changes (Chappuis et al., 2017).  Human-dominated landscapes increase the number of denitrified components of nitrogen in the system (i.e. ammonium and POM) through bacterial decomposition of anthropogenic sources of nitrogen (i.e. agriculture, sewage treatment, livestock manure). Because bacteria preferentially use 14N over 15N when breaking down these nitrogen components the remaining nitrogen from these components that enter the system have elevated d15N signatures (Di Lascio et al., 2013). The d15N values from anthropogenic sources of nitrogen have been shown to propagate up the food web. For example, in the Saint Lawrence lowlands in Quebec, Canada, primary consumer d15N values increased with the intensity of regional nitrogen loading from synthetic fertilizers and pig, chicken and cattle manure (Anderson & Cabana, 2006).  In the northeastern Unites States, watersheds dominated by natural forests had lower d15N values than watersheds dominated by urban or agricultural land (Mayer et al., 2002).  And in streams in northeastern Spain, d15N values of all basal resources were highest in human-impacted mainstem locations (Pastor et al., 2013).  In addition, land-use practices have been shown to elevate d15N values in lacustrine systems in Rhode Island (Lake et al., 2001) and boreal streams in south-central Sweden (Bergfur et al., 2009).  Thus, comparing food webs from sites dominated by different land uses can cause erroneous inferences into food web structure and function.

More accurate inferences can be achieved by applying a correction to consumer isotope ratio data that accounts for local variability in d15N among sample sites.  Trophic Position (TP) in particular is sensitive to variability in d15N and requires correction for better inferences (Kristensen et al., 2016). Such a correction can be achieved by modeling the d15N variability of all primary consumers in a system (Vander-Zanden & Rasmussen, 1999).  But the assessment of TP for higher level consumers can be confounded by inter-site difference in the d15N of basal resources (Hussey et al., 2014). A more promising approach is to develop a correction using an organism as a baseline proxy that reflects background d15N variation among sites (Cabana and Rasmussen 1996, Post 2002, Kristensen et al. 2016, Quezada-Romegialli et al. 2018) and that has a TP close to the higher level consumers (Hussey et al., 2014).  Although this baseline method is beginning to be applied in food web studies, it has limitations which require careful consideration before a proxy baseline is selected. Primary producers have short life cycles and high tissue turnover rates which prohibits useful interpretation of higher trophic levels due to differing temporal resolutions. So researchers have tended to collect all potential basal primary resources at a site (i.e., suspended and benthic organic matter, biofilms, filamentous algae, macrophytes, and riparian vegetation) in replicate multiple times across a given time interval (e.g., three times over growing period) and use the average d15N values of the primary producers as the baseline proxy value (Vinagre et al., 2008; Govender, Smit & Perissinotto, 2011). But collecting primary producers in streams is arduous and expensive because it requires many samples over many dates to adequately characterize baseline variation.  Therefore, long-lived primary consumers, particularly bivalves, with tissue turnover rates closer to higher level consumers are more appropriate than primary producers (Vander-Zanden & Rasmussen, 2001; Jardine et al., 2014). Bivalves also exhibit a uniform, specialized filter feeding strategy which can reduce additional variation in d15N attributable to omnivorous feeding habits. Unfortunately, bivalves and similar long-lived primary consumers are sparsely distributed in many temperate streams, rendering them impractical for such systems.  

Suitable primary consumer taxa to use as baseline indicators in temperate streams have only been identified for Danish lowlands and for an eastern Canadian watershed (Anderson & Cabana, 2007; Kristensen et al., 2016). But few detailed comparative tests exist, and a consensus needs to be reached for baseline indicators across regions. Therefore, our objective was to compare macroinvertebrate taxa and groups of taxa (i.e., functional feeding group; FFGs) as baseline indicators that reflect d15N values at the base of food web in streams that span the Rocky Mountain—Great Plaines ecotone in western North America. These streams vary in land-use characteristics moving from upstream headwaters to downstream reaches, making them opportune systems to identify a widely useable and reliable baseline indicator. We used four criteria to identify an optimal invertebrate baseline (Kristensen et al., 2016). The baseline taxon must: (1) have a wide geographic distribution, (2) have low with-in site variation of d15N values, (3) have d15N values that are correlated with background spatial variability in d15N, and (4) give trophic position estimates of organisms higher in the food web that are free of environment influences of d15N. As urbanization and agricultural land-use practices can influence d15N values in aquatic ecosystems (Mayer et al., 2002; Anderson & Cabana, 2005), the identification of regionally-derived baseline indicator organisms should aid in quantifying fish trophic position in stable isotope studies in lotic systems. 


## Methods

### Study site selection

We sampled sixteen 2nd-5th order stream sites distributed along the Rocky Mountain—Great Plains ecotone. Sites were selected to represent an environmental gradient based on elevation and land use that resulted in a wide variation of d15N values at the base of local food webs. Sites spanned the longitudinal (i.e., upstream-downstream) gradient of the three primary tributaries to the North Platte River in Wyoming, USA (Figure 1). The Sweetwater, Medicine Bow and Laramie rivers are snowmelt dominated with peak flows occurring in the spring and base flows occurring in mid-summer. Their watersheds transition from forested land at high elevations to agriculturally dominated land with some urbanization at low elevations.  

### Longitudinal gradient and land use index variable 

Instead of using percent natural land cover as a variable to compare d15N values among potential baselines (Kristensen et al., 2016), we used a proxy variable for a site’s location along the longitudinal stream gradient developed by Maitland (2020). The proxy variable combines seven metrics of environmental conditions at a study site into an index of longitudinal stream position using the Axis 1 site score from a principal component analysis (PCA). Input variables to the PCA were elevation (m a.s.l.), stream slope (km/km), distance to North Platte River (km), Strahler stream order, mean August water temperature (℃), upstream drainage area (km2), and stream width (m). This longitudinal gradient index (PC1) explained 78% of site-level variation among the 16 study sites and described changes in environmental conditions from upstream, high-elevation, cold-water streams to downstream, low-elevation, warm-water streams. Upstream sites were more likely to be surrounded by natural land cover (e.g. forest, grassland, shrubland, and wetland land types; NLCD Database 2011), as evidenced by a strong negative correlation between PC1 and percent natural landcover at a site (Pearson's correlation, r = -0.69, t15 = -3.66, P < 0.001; Maitland, 2020). Maitland (2020) also found that PC1 (and thus the degree of natural landcover) was positively correlated with d15N values of basal resources and primary consumers (Linear Regression - Basal Resources: F1,373 = 121.4, P < 0.001; Primary Consumers: F¬¬1,14 = 4.7, P = 0.050), consistent with previous research (Cabana and Rasmussen 1996, Lake et al. 2001, Kristensen et al. 2016). Thus, we used PC1 as a measure of local variation in d15N values for all future analyses. 
Sample collection and preparation

Samples were collected during summer 2016. Basal resources (i.e., primary uptake compartments) were sampled once in June, July, and August to account for fine-scale temporal variation in d15N (Jardine et al., 2014).  Seston was collected by filtering three replicates of up to 10 L of water onto pre-combusted (550 °C, 4 hours) filters (Whatman GF/F, 47 mm O) in the field using a modified portable drill pump (Kelso & Baker, 2016). Biofilm was collected by scraping five cobble-sized rocks within the reach.  Macroinvertebrates were collected during the same sampling events during the summer of 2016. A D-framed kick net was used in a variety of habitats (i.e. riffle, pools, macrophytes, and river margins) to collect a representative sample of the macroinvertebrate assemblage.  Macroinvertebrates were kept in filtered stream water for 24 hours to allow for gut clearance, then frozen. Muscle tissue samples were obtained from fish collected during the August sampling event using a backpack electrofishing unit (Smith-Root, Vancouver, WA).  Brown Trout Salmo trutta (Linnaeus, 1758), Creek Chub Semotilus atromaculatus (Person, Year), White Sucker Catostomus commersonii (Lacépède, 1803), were used because these species were found at greater than 50% of the sites.  To minimize the number of fish euthanized, a muscle plug using a 5-mm biopsy punch was taken from fish greater than 300 mm in length. The remaining fish used for SIA were euthanized with a lethal dose of MS-222, placed on ice and then frozen upon returning to the lab. Those fish not selected for SIA were returned to the stream. 

Macroinvertebrates were identified to family level using an invertebrate guide (Merritt et al. 2008). We classified macroinvertebrates into FFGs using a trait-based method. We obtained invertebrate trophic trait data from the USA Freshwater Biological Traits Database (Vieira et al. 2006), and then assigned trait affinity scores from 0 (absent) to 3 (strong affinity) using “fuzzy-coding” (Chevene et al. 1994). Because larvae and adults have different feeding behaviors, Elmidae were separated by life stage during identification.

<!-- When possible, we used individual macroinvertebrates for SIA but for small taxa we pooled individuals to ensure enough material for SIA. Muscle fillets were removed from the cranial dorsal portion of each fish. Samples were oven died (60 $^\circ$C, 48 hours), ground into a homogenous powder, and weighed to the nearest 0.001 mg. Animal samples (~1.0 mg) and basal resources (~2.0 mg) were weighed into 8 x 5-mm tin capsules and analyzed for d15N, d13C, %C, %N and C:N ratio at the University of Wyoming Stable Isotope Facility using a Delta Plus XP Continuous Flow Stable Isotope Ratio Mass Spectrometer (Thermo Finnigan, Bremen, Germany) coupled to a Costech Analytical 4010 elemental analyzer. Carbon (13C:12C) and nitrogen (15N:14N) isotope ratios (R) were estimated relative to their respective International Atomic Energy Agency standards (Pee Dee Belemnite limestone and atmospheric nitrogen). Working internal standards were run as controls throughout analysis to ensure accurate measurements. Isotopic values are reported in per mill delta notation \@ref(eq:ratio): -->

\begin{equation}
\delta^{n} = (\frac{R_{sample}}{R_{standard}}+1) * 100 (\#eq:ratio)
\end{equation}

where dN is either N15 or c13, and R is the ratio of the heavy to lighter isotope. Analytical error (i.e., 1 SD of lab standard) of sample runs was estimated at 0.07‰ (d13C) and 0.18‰ (d15N) for the invertebrates, and 0.04‰ (d13C) and 0.10‰ (d15N) for the fish. 

### Baseline selection

Suitability of various macroinvertebrate taxa as baselines were based on the four criteria proposed by Kristensen et al. (2016).  The baseline taxon must: (1) have a wide geographic distribution, (2) have low with-in site variation of d15N values, (3) have d15N values correlated with environmental influences of d15N, (4) give trophic positions estimates of other consumers free of environment influences of d15N.  Although all analyses were performed for all macroinvertebrate taxa and FFGs, selection occurred progressively from each criterion. For example, if a macroinvertebrate taxon met the first criterion it would stay in the list of potential baselines and be evaluated for the second criterion, but if it did not meet the first criterion then it would be removed from the list. 

#### Criteria 1: Geographic Distribution 

The geographic distribution was expressed as the percentage of the 16 sites that contained a given macroinvertebrate taxon. We used a cut off of 75% of sites in the selection process as a reasonable value for identifying a widely distributed taxon.  Although 75% was chosen arbitrarily, Kristenson et al. (2016) included two taxa that would fall below this mark, and the best baseline identified by Kristenson et al. (2016) was found at 78.9% of sites. This makes our cutoff a more conservative measure of distribution while retaining the distribution levels of the best baselines in other studies.

#### Criteria 2: Low Coefficient of Variation 

We calculated the coefficient of variation (CV) of d15N values for all macroinvertebrate taxa and FFGs. A low coefficient of variation for d15N indicates that a baseline candidate has a non-omnivorous diet. To calculate CV, we divided the standard deviation of d15N signatures by the mean d15N signature of each baseline candidate at each site.  We then found the mean and 95% confidence intervals for each baseline candidate across sites. 

We use one-way analysis of variance (ANOVA) to test for differences in CV values among baselines. Separate analyses were done on individual taxa and FFGs.  The CV values were square root or log transformed to ensure normality.  We used the Tukey HSD post hoc tests for pairwise-comparison using an alpha of 0.05.

#### Criteria 3: Correlation with Longitudinal Gradient 

For all macroinvertebrate taxa and FFGs, we used least squares linear regression to assess relationships between the baseline’s d15N position at sites along the longitudinal stream gradient.  We wished to compare our baselines’ relationships to the longitudinal gradient with those of the basal resources. So, we did separate least squares linear regressions for two of the basal resources at our sites and compared R2 values between the baselines and the resources at our sites.  The R2 value of our basal resources represent the minimum level of variation that our alternate baselines should explain in order to be used as alternatives to the traditional method (e.g. all basal resources across a season).   
<!-- Baselines with significant ($P \le 0.05$) relationships with the longitudinal gradient and that had R2 values equal to or greater than the basal resources were considered suitable baselines. -->

#### Criteria 4: Trophic Position Estimates Independent of Longitudinal Gradient

We calculated trophic positions for Brown Trout, Creek Chub, and White Sucker using each macroinvertebrate taxa and FFG as a baseline following (Post, 2002):

<!-- \begin{equation} -->

<!-- \end{equation} -->

where TPConsumer is the trophic position of each individual fish at a site, d15NConsumer is the d15N signature of each individual fish, d15NBaseline is the mean d15N signature of the baseline at each site, d15N is the discrimination factor for each trophic transfer, and TLBaseline is the expected trophic level of the baseline. Discrimination factor were estimated using the methods of Caut et al. (2009).  

To assess the difference between corrected TP estimates and uncorrected TP estimates of Brown Trout, Creek Chub, and White Sucker, we modified the above equation by removing the baseline correction. The resulting formula is:

<!-- \begin{equation} -->

<!-- \end{equation} -->

We use analysis of covariance (ANCOVA) to test for differences in slopes among baselines and FFGs. Separate analyses were done on taxa and FFG.  The TP estimates were square root or log transformed to ensure normality.  After each ANCOVA, we used the Tukey HSD method for pairwise-comparison across each baseline. All analysis was done in R version 3.2 (R Core Team, 2019). 


## Results

### Criteria 1: Geographic Distribution

We found 21 macroinvertebrate families among our study sites. We split one family (Elmidae) into two groups based on life stage. Eight taxa were found in at least 75% of sites.  Chironomidae, Elmidae-larvae, Elmidae-adult, Heptaganeidae, and Hydropyschidae were the most common taxa and were found at all sites (Table 1). Perlidae was the least common taxon and was found at six sites. Collectors, Grazers, Filterers, and Aquatic Predators were the most common functional feeding groups (FFG) and were found at all sites. Shredders were only found at 63% of sites. Twelve baselines (8 taxa, 4 FFGs) were considered sufficiently distributed and used in further analysis.

### Criteria 2: Low Coefficient of Variation

We calculated the coefficient of variation (CV) for d15N at each site for the 12 sufficiently distributed baselines (8 taxa, 4 FFGs).  We found significant differences in the CVs for the taxa (ANOVA test; F11,26 = 2.96, P = 0.002; Figure 2). Simuliidae had the smallest CV across sites and Elmidae-adult had the largest (Figure 2).  Additionally, Simuliidae were 0.19 units lower than Elmidae-adult, 0.17 units lower than Chironimidae, and, although marginally significant, 0.15 units lower than Elmidae-larvae (Tukey HSD tests; P = 0.011 for Elmidae-adult; P = 0.032 for Chironomidae; P =  0.071 for Elmidae-adult; Figure 2).  Simuliidae were not statistically different from Dytiscidae, Baetidae, Heptaganeidae and Hydropyschidae. We found marginally significant differences among the FFG baselines (ANOVA test; F3,57 = 2.49, P = 0.070; Figure 2). Filterers were 0.18 units lower than Grazers (Tukey HSD tests; P = 0.047; Figure 2).  Filterers were not statistically different from Predators or Collectors.

### Criteria 3: Correlation with Environmental d15N 

The two basal resources, biofilm and seston, had d15N signatures that were significantly (P > =  0.05) correlated with the longitudinal stream gradient (PC1) (Figure 3; Table 1). All eight of the well distributed taxa and all FFG’s had d15N signatures that were significantly correlated with PC1 (Figure 3). The amount of variation in d15N signatures captured by the longitudinal gradient was similar among the two basal resources, eight sufficiently distributed taxa and the four FFGs.

### Criteria 4: Trophic Position Estimates Independent of Environmental d15N

When using the FFGs as a baseline, uncorrected Trophic Position (TP) estimates for Brown Trout were strongly positively correlated with the longitudinal gradient emphasizing the need for baseline correction (Figure 4; Figure 5).  Correction of the TP using the different FFGs as baselines significantly reduced the strength the longitudinal gradient had on TP estimates (Figure 4; Figure 5).  After baseline correction, Brown Trout TP estimates still increased with PC1 (Figure 4).  There were no differences in slopes between Brown Trout TP and the longitudinal gradients given by the different FFG baselines (Figure 5).  Brown Trout TP estimates differed by FFG baseline (ANOVA test: F3,1488 = 11.67; P < 0.001). On average grazers gave higher trophic position estimates for Brown Trout than filterers and predators and collectors gave higher trophic position estimates for Brown Trout that predators (Figure 6; Supplemental Table 2).  

When using the FFGs as a baseline, uncorrected TP estimates for Creek Chub were strongly positively correlated with the longitudinal gradient (Figure 4; Figure 7; Supplemental Table 1). Correction of the TP significantly reduced the strength the longitudinal gradient had on TP estimates (Figure 4; Figure 7).  After correction, Creek Chub TP estimates were generally not influenced by PC1 (Figure 4; Figure 7).  There were no differences between slopes of Creek Chub TP estimates and the longitudinal gradient among filterers, grazers and collectors but predators were lower (ANOVA test : F3,1398 = 22.27; P < 0.001;  Supplemental Table 2).  

When using the FFGs as a baseline, uncorrected TP estimates for White Sucker were strongly positively correlated with the longitudinal gradient (Figure 4; Figure 7; Supplemental Table 1).  Correction of the TP using different FFGs significantly reduced the strength the longitudinal gradient had on TP estimates (Figure 4; Figure 7).  After correction, White Sucker TP estimates were slightly negatively correlated with PC1 (Figure 4; Figure 7).  The slope of White Sucker TP estimates and the longitudinal gradient given by predators was significantly lower than the slopes of the other FFGs (Figure 7 ANOVA test : F3,1142 = 26.85; P < 0.001 ; Supplemental Table 2).  

Similar to FFG’s, correction of the TP using different taxa significantly reduced the effect of the longitudinal gradient on TP estimates (Figure 5; Figure 7; Supplemental Table 1).  The slope of Brown TP estimates and PC1 was lower for all taxa than when using uncorrected estimates (Figure 7). After correction, Brown Trout TP estimates were positively correlated with the longitudinal gradient when using Hydropyschidae, Baetidae, Simulidae, Dytiscidae, Elmidae-larvae, and Elmidae-adult.  Brown Trout TP estimates were not correlated with the longitudinal gradient when using Heptaganeidae and Chironomidae as baselines. Brown Trout trophic position estimates differed by baseline taxa (ANOVA test: F7,2787 = 68.76; P < 0.001). 

Brown Trout TP estimates given by Elmidae-adult and Elmidae-larvae were higher than the other taxa (Figure 6; Supplemental Table 2). Hydropyschidae and Heptaganeidae gave lower Brown Trout TP estimates than the other except Chironomidae and Baetidae for which they did not differ (Figure 6; Supplemental Table 2).  Dytiscidae and Simulidae gave intermediate Brown Trout TP estimates (Figure 6; Supplemental Table 2).

Correction of the TP for Creek Chub generally reduced the strength the longitudinal gradient had on TP estimate (Figure 5; Figure 7; Supplemental Table 1).  Hydopyschidae, Dytiscidae, Elmidae-adult, Elmidae-larvae, and Chironomidae had slopes of Creek Chub TP estimates and PC1 that were lower than the uncorrected (Figure 7). Baetidae, Simulidae, and Heptaganeidae had slopes that were not different than uncorrected (Figure 7).  Creek Chub TP estimates were not correlated with the environmental gradient using Hydopyschidae, Simulidae, Elmidae-larvae, Elmidae-adult, and Chironomidae as baselines (Figure 7). When using Baetidae and Heptaganeidae as baselines, Creek Chub TP estimates were positively correlated with PC1 (Figure 7).  Creek Chub TP estimates were negatively correlated with PC1 when using Dytiscidae (Figure 7). Creek Chub TP estimates differed between baseline taxa (ANOVA test: F7,2480 = 42.56; P < 0.001).  Elmidae-adult and Elmidae-larvae gave the highest Creek Chub TP estimates (Figure 6; Supplemental Table 2).  Hydropyschidae gave the lowest Creek Chub TP estimates but were not different from Chironomidae and Heptaganeidae (Figure 6; Supplemental Table 2). Simulidae, Dytiscidae and Baetidae gave intermediate TP estimates for Creek Chub (Figure 6; Supplemental Table 2).

Correction of the TP for White Sucker reduced the strength that the longitudinal gradient had on TP estimates (Figure 5; Figure 7; Supplemental Table 1).  Slopes of White Sucker TP estimates and PC1 were lower than uncorrected for all baseline taxa (Figure 7).  White Sucker TP estimates were not correlated with PC1 when using Baetidae, Elmidae-adults, and Chironomidae as baselines (Figure 7).  When using Hydropyschidae, Simulidae, Dytiscidae, Elmidae-larvae, and Heptaganeidae as baselines, White Sucker TP estimates were negatively correlated with PC1 (Figure 7).  White Sucker TP estimates differed by baseline taxa (ANOVA test: F7,2008 = 44.91; P < 0.001).  Elmidae-adult and Elmidae-larvae gave the hightest Creek Chub TP estimates (Figure 6; Supplemental Table 2).  Hydropyschidae gave the lowest Creek Chub TP estimates but was not different from Dytiscidae, Chironomidae, and Heptaganeidae (Figure 6; Supplemental Table 2).  Simulidae and Baetidae gave intermediate Creek Chub TP estimates (Figure 6; Supplemental Table 2).

## Discussion

Of the 21 taxa and 5 FFGs, 8 taxa and 4 FFGs were found at greater than 75% of sites (Criterion 1).  Of the well distributed taxa and FFGs, 3 taxa (i.e., Elmidae-adult, Elmidae-larvae, and Chironimidae) and one FFG (i.e., grazers) were removed because of high CVs relative to the respective taxa and FFGs (Criterion 2). Of the 5 taxa and 3 FFGs that remained, all were correlated with the longitudinal gradient (Criterion 3).  When looking at TP estimates of three fishes, no single baseline removed the effect of the longitudinal gradient on TP across fishes (i.e., nonsignificant slopes, Figure 7; Criterion 4) which would suggest that the best baseline would depend on fish species.  But when comparing TP estimated using baselines and TP estimated using stomach contents, simuliidae and filters gave TP slopes similar to stomach contents across all fishes (Figure 7; Criterion 4) which indicates that Simuliidae and filterers would be the best baselines from their respective groups.

General synthesis of the baselines through the criteria. This would include the discussion on if a FFG could be used instead

Difference between Kristeson’s findings in Criteria 4 that there was no change in TP in their study.  Ours definitely is showing a change in TP for BNT and WHS.
compare the baselines with those found in Danish streams and Canadian water sheds


## Acknowledgements:

The University of Wyoming Research Scholars provided funding for this research. Fish were collected under University of Wyoming IACUC Protocol #20160630FR00245-01, and in accordance with Wyoming Game and Fish Department Chapter 33 permit #1077. We thank landowners for allowing property access. T. Allison, C. Carlson, R. Walker, and R. Davis assisted with field and laboratory work.  XXX provided helpful comments on earlier versions of this manuscript. 

## Figure Captions

Figure 1: Map of the study area within the North Platte River drainage. LR corresponds to sites in the Laramie River, MB correspond to sites in the Medicine Bow River, and SW correspond to sites in the Sweet Water River.

Figure 2. Each baseline’s mean Coefficient of Variation (CV) of d15N across sites with 90% confidence intervals. A) Taxon baselines B) FFG baselines.  All baselines met Criteria 1 of being found in at least 75% of study sites. 

Figure 3. Relationships between the d15N values of A) basal resources, B) FFGs, and C) taxa in relation to position along the longitudinal gradient represented by PC1.  Each point is the mean d15N signature of the baseline candidate or basal resource at that site. Upstream sites are to the left. The black line is the fitted regression line and the shaded grey represents the 95% confidence interval.  See Supp. Table 1 for full statistical results.

Figure 4. The trophic position estimate of each fish species as a function of the environmental gradient.  Grey dots correspond to fish trophic positions without using a baseline correction. Black dots correspond to fish trophic positions after applying a baseline correction using the indicted FFG. Lines represent the estimated trend line and shaded areas represent the 95% confidence interval. Statistics presented on the panels correspond to the corrected values. See Supp. Table 2 for full statistical results.

Figure 5: regression slope coefficients and 95% confidence intervals given by each baseline for the relationships between TP estimates and the longitudinal gradient (filled circles).  The uncorrected baseline slope and 95% confidence interval is also given (open circle). 

Figure 6. The trophic position estimate of each fish species as a function of the environmental gradient.  Grey dots correspond to fish trophic positions without using a baseline correction. Black dots correspond to fish trophic positions after applying a baseline correction using the indicted FFG. Lines represent the estimated trend line and shaded areas represent the 95% confidence interval. Statistics presented on the panels correspond to the corrected values   See Supp. Table 2 for full statistical results.

## References

